name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # jalan tiap tengah malam UTC
  workflow_dispatch:      # bisa dijalankan manual lewat Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # IZIN agar bisa push ke repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: HaikalRiyadh
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # jalan tiap tengah malam UTC
  workflow_dispatch:      # bisa dijalankan manual lewat Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # IZIN agar bisa push ke repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: HaikalRiyadh
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
